### ISSUE TITLE
Quest book make th game crash

### ISSUE THREAD

**Issue by JeanGuyTheJanitor** [MarsmoucheStudio/DiabloTL#5]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

when reading some quest book the game crash. Fix this grand code master

### To Reproduce

1-open Theodore's lair
2-go to lvl 13 
3-read the book of warlord of blood

### Expected Behavior

see text and the game dont crash

### Additional context

with the new class the cleric

**Comment by dinde451** [comment]
fix! download the new release :-)
